-- Reemplazando con los 9 productores y 9 productos reales del marketplace
-- Insertar los 9 productores reales del marketplace
INSERT INTO producers (name, location, region, specialty, description, image_url, certification, rating, total_reviews) VALUES
('María Elena Rodríguez - Finca El Paraíso', 'Huila, Colombia', 'Huila', 'Café de Altura', 'Productora de tercera generación con 25 años de experiencia. Combina técnicas tradicionales con métodos modernos y sostenibles.', '/productora-maria-elena-rodriguez.jpg', 'Orgánico, Comercio Justo, Rainforest Alliance', 4.8, 127),
('Carlos Andrés Muñoz - Hacienda Los Andes', 'Nariño, Colombia', 'Nariño', 'Café Especial', 'Innovador en café especial con 18 años de experiencia. Experimenta con métodos de fermentación únicos.', '/productor-de-caf--colombiano-carlos-andr-s.jpg', 'Rainforest Alliance, Comercio Justo', 4.9, 89),
('Juan Pablo Ramírez - Finca La Esperanza', 'Eje Cafetero, Colombia', 'Eje Cafetero', 'Café Tradicional', 'Mantiene viva la tradición cafetera con 22 años de experiencia. Su finca es santuario de aves migratorias.', '/productor-juan-pablo-eje-cafetero.jpg', 'Orgánico, Bird Friendly', 4.7, 156),
('Ana María Vargas - Finca Los Andes', 'Tolima, Colombia', 'Tolima', 'Café Gourmet', 'Innovadora en procesos de beneficio con 15 años de experiencia. Mentora de jóvenes caficultoras.', '/productora-ana-maria-tolima.jpg', 'Orgánico, Comercio Justo', 4.8, 73),
('Pedro Antonio Gómez - Finca San José', 'Cauca, Colombia', 'Cauca', 'Café Artesanal', 'Maestro del café artesanal con 28 años de experiencia. Preserva tradiciones ancestrales.', '/productor-pedro-cauca.jpg', 'Orgánico, Rainforest Alliance', 4.9, 92),
('Roberto Silva - Hacienda El Roble', 'Santander, Colombia', 'Santander', 'Café Tradicional', 'Representa la tradición cafetera de Santander con 20 años de experiencia. Líder en comercio justo.', '/productor-roberto-santander.jpg', 'UTZ Certified, Comercio Justo', 4.6, 134),
('Claudia Patricia Moreno - Finca Vista Hermosa', 'Quindío, Colombia', 'Quindío', 'Café Premium', 'Transformó una finca abandonada en productora premium con 17 años de experiencia. Modelo de biodiversidad.', '/productora-claudia-quindio.jpg', 'Orgánico, Rainforest Alliance, Bird Friendly', 4.8, 108),
('Diego Fernando Ospina - Finca El Mirador', 'Valle del Cauca, Colombia', 'Valle del Cauca', 'Café Especial', 'Pionero en café especial con 19 años de experiencia. Experimenta con métodos de procesamiento.', '/productor-diego-valle.jpg', 'Orgánico, UTZ Certified', 4.7, 85),
('Sofía Martínez - Finca Tierra Verde', 'Boyacá, Colombia', 'Boyacá', 'Café Orgánico', 'Joven productora revolucionando el café orgánico con 12 años de experiencia. Líder en agricultura regenerativa.', '/productora-sofia-boyaca.jpg', 'Orgánico, Comercio Justo, Rainforest Alliance', 4.9, 67);

-- Insertar los 9 productos reales del marketplace
INSERT INTO products (producer_id, name, description, origin, region, price, stock, image_url, roast_level, flavor_notes, altitude, process_method, rating, total_reviews, is_featured, is_organic) VALUES
(1, 'Café Huila Premium', 'Un café excepcional cultivado en las montañas de Huila, conocido por su perfil de sabor equilibrado y notas dulces distintivas.', 'Huila, Colombia', 'Huila', 45000, 15, '/caf--huila-premium-bolsa-de-caf--colombiano.jpg', 'medium', ARRAY['Chocolate', 'Frutos Rojos', 'Caramelo'], '1600-1800 msnm', 'Lavado', 4.8, 127, true, true),
(2, 'Nariño Especial', 'Café de altura excepcional de Nariño, con notas florales y cítricas que lo hacen único. Perfecto para métodos de filtrado.', 'Nariño, Colombia', 'Nariño', 52000, 12, '/caf--nari-o-especial-bolsa-premium.jpg', 'light', ARRAY['Cítricos', 'Miel', 'Flores'], '1800-2200 msnm', 'Lavado', 4.9, 89, true, true),
(3, 'Eje Cafetero Clásico', 'El sabor tradicional del café colombiano. Cuerpo robusto y notas intensas, ideal para espresso y preparaciones fuertes.', 'Eje Cafetero, Colombia', 'Eje Cafetero', 38000, 20, '/caf--eje-cafetero-cl-sico-bolsa-tradicional.jpg', 'dark', ARRAY['Nueces', 'Chocolate Oscuro', 'Panela'], '1400-1600 msnm', 'Natural', 4.7, 156, false, true),
(4, 'Tolima Gourmet', 'Café gourmet de Tolima con perfil complejo y balanceado. Notas tropicales y dulces que sorprenden en cada taza.', 'Tolima, Colombia', 'Tolima', 48000, 8, '/caf--tolima-gourmet-bolsa-premium.jpg', 'medium', ARRAY['Frutas Tropicales', 'Vainilla', 'Almendras'], '1500-1700 msnm', 'Honey', 4.8, 73, true, true),
(5, 'Cauca Artesanal', 'Café artesanal de las montañas del Cauca, procesado con métodos tradicionales que resaltan su dulzura natural y notas florales delicadas.', 'Cauca, Colombia', 'Cauca', 55000, 10, '/cafe-cauca-artesanal-bolsa.jpg', 'light', ARRAY['Jazmín', 'Durazno', 'Azúcar Morena'], '1700-2000 msnm', 'Lavado', 4.9, 92, true, true),
(6, 'Santander Tradicional', 'Café robusto de Santander con carácter intenso. Perfecto para quienes buscan un café con cuerpo y sabor tradicional colombiano.', 'Santander, Colombia', 'Santander', 42000, 18, '/cafe-santander-tradicional-bolsa.jpg', 'dark', ARRAY['Cacao', 'Especias', 'Caña de Azúcar'], '1300-1500 msnm', 'Natural', 4.6, 134, false, false),
(7, 'Quindío Premium', 'Café premium del corazón del Eje Cafetero. Balance perfecto entre dulzura y acidez, con notas frutales y de frutos secos.', 'Eje Cafetero, Colombia', 'Quindío', 47000, 14, '/cafe-quindio-premium-bolsa.jpg', 'medium', ARRAY['Caramelo', 'Manzana Roja', 'Avellana'], '1500-1700 msnm', 'Lavado', 4.8, 108, true, true),
(8, 'Valle del Cauca Especial', 'Café especial del Valle del Cauca con perfil delicado y complejo. Notas cítricas brillantes y dulzura natural que lo hacen excepcional.', 'Valle del Cauca, Colombia', 'Valle del Cauca', 49000, 9, '/cafe-valle-cauca-especial-bolsa.jpg', 'light', ARRAY['Mandarina', 'Miel de Abeja', 'Té Blanco'], '1600-1900 msnm', 'Honey', 4.7, 85, true, true),
(9, 'Boyacá Orgánico', 'Café 100% orgánico de Boyacá, cultivado sin químicos en armonía con la naturaleza. Sabor limpio con notas dulces y frutales.', 'Boyacá, Colombia', 'Boyacá', 53000, 11, '/cafe-boyaca-organico-bolsa.jpg', 'medium', ARRAY['Frutos del Bosque', 'Chocolate con Leche', 'Miel'], '1800-2100 msnm', 'Lavado', 4.9, 67, true, true);
